config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root 'pages#home'
  get 'about', to: 'pages#about'
end

# i% [crea un array de simbolos sin comas]
# w% [crea un array de strings sin comas]

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: { minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 6, maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: %i[show edit update destroy]

  # antes de hacer show, edit, update y destroy, se hará un set_article, y luego la acción show o edit o update o destroy

  def show

    
    #  @article = Article.find(params[:id]) es lo mismo que poner por consola (article = Article.find(1))
    # se tiene que poner @article ara que "article" sea available para la vista "show"
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new 
    
    # @article = Article.new se tiene que poner porque cada vez que entramos en "new", la vista tiene un "@article" que no reconoce
    # si esto se queda vacío, entra en la vista "new" pero "@article" no existe porque se encuentra en "create"
    # por tanto hay que crear esta variable @article
  end

  def edit
    
    # sirve para poner /:d/edit, per una vez le damos a actualizar, la consola del server nos dice que no encuentra
    # un template para "update"

  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated"
    redirect_to @article
    else
      render 'edit'
    end
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was successfully created"
    redirect_to @article
    else
      render 'new'
    end
  end

  def destroy

    @article.destroy
    redirect_to articles_path
  end

  private # todo lo que ponga aquí será visible para todos los métodos de este controlador únicamente.

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
    <h2>The following errors occurred:</h2>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>


<%= form_with(model: @article, local: true) do |f| %>

    <p>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label :description %>
        <%= f.text_area :description %>
    </p>

    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>


<%= render 'form' %>

<%= link_to 'Cancel and return to articles', articles_path %>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Delete', article_path(article), method: :delete, data: { confirm:"Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to 'Create a new article', new_article_path %>
</p>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>


<%= link_to 'Back to articles', articles_path %>

app/views/articles/show.html.erb
<h1>showing article details</h1>
<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>description: </strong><%= @article.description %></p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm:"Are you sure?" } %> |
<%= link_to 'Back to articles', articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
      <%= msg %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to the About page</h1>

<%= link_to 'Articles listing', articles_path %>
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<h1>Welcome to the home page</h1>

<%= link_to 'Articles listing', articles_path %>
<%= link_to 'About page', about_path %>